import google.generativeai as genai
from PIL import Image, ImageDraw, ImageFont, ImageFilter
from pathlib import Path
from typing import Optional, Dict, List
import textwrap
import hashlib


class ImageGenerator:
    """Generate images from text using Gemini AI"""
    
    def __init__(self, api_key: str):
        genai.configure(api_key=api_key)
        self.model = genai.GenerativeModel('gemini-pro')
        
    def create_visual_prompt(self, text: str, style: str = "professional") -> str:
        """
        Create a detailed image generation prompt from text
        
        Args:
            text: Input text to convert to visual concept
            style: Visual style (professional, creative, minimal, technical)
        """
        prompt = f"""
        Based on the following text, create a detailed description for a professional 
        infographic or visualization that would represent these concepts visually.
        
        Text: {text[:500]}
        
        Requirements:
        - Style: {style}, corporate, clean
        - Color scheme: Professional blues, whites, accent colors
        - Include: Key concepts, data points, relationships
        - Avoid: Clutter, too much text, complex diagrams
        
        Provide a concise visual description (max 100 words) that could be used 
        to generate an image.
        """
        
        try:
            response = self.model.generate_content(prompt)
            return response.text
        except Exception as e:
            return f"Professional infographic representing: {text[:100]}"
    
    def generate_text_image(
        self, 
        text: str, 
        title: str = "Summary",
        output_path: Optional[str] = None,
        width: int = 1024,
        height: int = 768,
        style: Dict = None
    ) -> str:
        """
        Generate an image with formatted text
        
        Args:
            text: Main text content
            title: Title for the image
            output_path: Where to save the image
            width: Image width in pixels
            height: Image height in pixels
            style: Style configuration dict
        """
        # Default style
        if style is None:
            style = {
                'bg_color': '#FFFFFF',
                'title_color': '#0066CC',
                'text_color': '#333333',
                'accent_color': '#00A3E0',
                'font_title_size': 48,
                'font_text_size': 24
            }
        
        # Create image
        img = Image.new('RGB', (width, height), color=style['bg_color'])
        draw = ImageDraw.Draw(img)
        
        # Try to load custom fonts, fallback to default
        try:
            font_title = ImageFont.truetype("arial.ttf", style['font_title_size'])
            font_text = ImageFont.truetype("arial.ttf", style['font_text_size'])
            font_small = ImageFont.truetype("arial.ttf", 18)
        except:
            font_title = ImageFont.load_default()
            font_text = ImageFont.load_default()
            font_small = ImageFont.load_default()
        
        # Draw accent bar at top
        draw.rectangle([(0, 0), (width, 10)], fill=style['accent_color'])
        
        # Draw title
        title_y = 40
        draw.text((50, title_y), title, font=font_title, fill=style['title_color'])
        
        # Draw separator line
        draw.line([(50, title_y + 60), (width - 50, title_y + 60)], 
                  fill=style['accent_color'], width=3)
        
        # Wrap and draw main text
        text_y = title_y + 100
        margin = 50
        max_width = width - (2 * margin)
        
        # Wrap text to fit width
        wrapper = textwrap.TextWrapper(width=60)
        wrapped_lines = []
        for line in text.split('\n'):
            if line.strip():
                wrapped_lines.extend(wrapper.wrap(line))
        
        # Draw text lines
        line_height = style['font_text_size'] + 10
        for i, line in enumerate(wrapped_lines[:15]):  # Limit to 15 lines
            if text_y + (i * line_height) < height - 100:
                draw.text((margin, text_y + (i * line_height)), 
                         line, font=font_text, fill=style['text_color'])
        
        # Add footer
        footer_text = "Generated by AI Content Generator"
        draw.text((margin, height - 40), footer_text, 
                 font=font_small, fill=style['text_color'])
        
        # Add subtle shadow effect
        img = img.filter(ImageFilter.SMOOTH)
        
        # Save image
        if output_path is None:
            output_path = f"output_{hashlib.md5(text.encode()).hexdigest()[:8]}.png"
        
        img.save(output_path, quality=95)
        print(f"Image saved: {output_path}")
        
        return output_path
    
    def create_summary_visualization(
        self, 
        summary_data: Dict,
        output_path: str,
        template: str = "modern"
    ) -> str:
        """
        Create a visual summary from structured data
        
        Args:
            summary_data: Dict with title, key_points, sections
            output_path: Where to save the image
            template: Visual template name
        """
        width, height = 1920, 1080  # Full HD
        
        if template == "modern":
            style = {
                'bg_color': '#F8F9FA',
                'title_color': '#1E3A8A',
                'text_color': '#374151',
                'accent_color': '#3B82F6',
                'font_title_size': 64,
                'font_text_size': 28
            }
        else:
            style = {
                'bg_color': '#FFFFFF',
                'title_color': '#0066CC',
                'text_color': '#333333',
                'accent_color': '#00A3E0',
                'font_title_size': 56,
                'font_text_size': 26
            }
        
        # Extract content
        title = summary_data.get('title', 'Summary')
        key_points = summary_data.get('key_points', [])
        
        # Combine key points into text
        text_content = "\n\n".join([f"• {point}" for point in key_points[:8]])
        
        return self.generate_text_image(
            text=text_content,
            title=title,
            output_path=output_path,
            width=width,
            height=height,
            style=style
        )
